In [ ]:
Dataset Description:
The dataset contains information about 300 cars from different brands and countries. 
It includes features such as engine size, horsepower, mileage, transmission type, fuel type, price, 
and manufacturing details.
Target Variable:
Efficiency_Score – a numerical value that represents the overall efficiency of the car.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

Task 1: Identify Data Quality Issues

In [2]:
pd.set_option("display.max_columns", None)

df = pd.read_excel("global_cars_enhanced.xlsx")
df.head(10)

,global_cars_enhanced,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,Car_ID,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score
1,CAR_0001,Mercedes,2006,SUV,Petrol,Manual,4089,547,17,73407,USA,20,Premium,0.1338,Old,0.35
2,CAR_0002,Nissan,2023,Coupe,Petrol,Automatic,4618,167,25,79370,USA,3,Premium,0.0362,New,0.75
3,CAR_0003,Nissan,2007,Hatchback,Diesel,Manual,1802,110,16,76549,China,19,Premium,0.061,Old,0.3
4,CAR_0004,Nissan,2013,Coupe,Petrol,Manual,1835,373,16,48722,USA,13,Mid-Range,0.2033,Old,0.3
5,CAR_0005,Hyundai,2009,Hatchback,Hybrid,Automatic,2332,145,28,83265,UK,17,Premium,0.0622,Old,0.9
6,CAR_0006,Tesla,2012,Coupe,Diesel,Automatic,2124,321,19,63134,UK,14,Premium,0.1511,Old,0.45
7,CAR_0007,Audi,2011,Hatchback,Petrol,Automatic,4527,342,29,74241,Japan,15,Premium,0.0755,Old,0.95
8,CAR_0008,Tesla,2016,SUV,Diesel,Automatic,1729,309,20,54364,China,10,Mid-Range,0.1787,Moderate,0.5
9,CAR_0009,Audi,2017,Hatchback,Hybrid,Manual,1561,470,12,65750,Germany,9,Premium,0.3011,Moderate,0.1

In [22]:
# set first row as column names
df.columns = df.iloc[0]

# drop the first row
df = df.drop(0)

# reset index
df = df.reset_index(drop=True)

df.head()

,Car_ID,Brand,Manufacture_Year,Body_Type,Fuel_Type,Transmission,Engine_CC,Horsepower,Mileage_km_per_l,Price_USD,Manufacturing_Country,Car_Age,Price_Category,HP_per_CC,Age_Category,Efficiency_Score
0,CAR_0001,Mercedes,2006,SUV,Petrol,Manual,4089,547,17,73407,USA,20,Premium,0.1338,Old,0.35
1,CAR_0002,Nissan,2023,Coupe,Petrol,Automatic,4618,167,25,79370,USA,3,Premium,0.0362,New,0.75
2,CAR_0003,Nissan,2007,Hatchback,Diesel,Manual,1802,110,16,76549,China,19,Premium,0.061,Old,0.3
3,CAR_0004,Nissan,2013,Coupe,Petrol,Manual,1835,373,16,48722,USA,13,Mid-Range,0.2033,Old,0.3
4,CAR_0005,Hyundai,2009,Hatchback,Hybrid,Automatic,2332,145,28,83265,UK,17,Premium,0.0622,Old,0.9

In [3]:
df.dtypes

global_cars_enhanced    object
Unnamed: 1              object
Unnamed: 2              object
Unnamed: 3              object
Unnamed: 4              object
Unnamed: 5              object
Unnamed: 6              object
Unnamed: 7              object
Unnamed: 8              object
Unnamed: 9              object
Unnamed: 10             object
Unnamed: 11             object
Unnamed: 12             object
Unnamed: 13             object
Unnamed: 14             object
Unnamed: 15             object
dtype: object

In [4]:
df.isna().sum()

global_cars_enhanced    0
Unnamed: 1              0
Unnamed: 2              0
Unnamed: 3              0
Unnamed: 4              0
Unnamed: 5              0
Unnamed: 6              0
Unnamed: 7              0
Unnamed: 8              0
Unnamed: 9              0
Unnamed: 10             0
Unnamed: 11             0
Unnamed: 12             0
Unnamed: 13             0
Unnamed: 14             0
Unnamed: 15             0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.describe()

,global_cars_enhanced,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
count,301,301,301,301,301,301,301,301,301,301,301,301,301,301,301,301
unique,301,11,22,6,5,3,288,221,22,301,7,22,5,285,5,30
top,Car_ID,Nissan,2020,Sedan,Petrol,Manual,3642,165,24,Price_USD,Germany,6,Budget,0.0732,Old,0.7
freq,1,41,27,70,77,155,2,4,21,1,55,27,78,2,126,21


Task 2: Apply one missing value strategy and explain why

In [9]:
df_missing = df.copy()
df_missing.loc[0:5, 'Price_USD'] = np.nan
df_missing['Price_USD'] = df_missing['Price_USD'].fillna(df_missing['Price_USD'].median())
df_missing.isna().sum()

global_cars_enhanced      0
Unnamed: 1                0
Unnamed: 2                0
Unnamed: 3                0
Unnamed: 4                0
Unnamed: 5                0
Unnamed: 6                0
Unnamed: 7                0
Unnamed: 8                0
Unnamed: 9                0
Unnamed: 10               0
Unnamed: 11               0
Unnamed: 12               0
Unnamed: 13               0
Unnamed: 14               0
Unnamed: 15               0
Price_USD               301
dtype: int64

Median was selected because it is more robust to outliers compared to the mean, especially if the Price column contains extreme values.

Task 3: Detect and handle outliers using IQR

In [26]:

Q1 = df_clean['Price_USD'].quantile(0.25)
Q3 = df_clean['Price_USD'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Detect outliers
outliers = df_clean[(df_clean['Price_USD'] < lower) | (df_clean['Price_USD'] > upper)]
print("Number of outliers:", outliers.shape[0])

Number of outliers: 0

Using the IQR method on the Price_USD column, no outliers were detected since no values fell outside the lower and upper bounds. This indicates that the price distribution is relatively stable and does not contain extreme values.

Task 4: Normalize numerical features using Min-Max and Z-score

In [28]:
df['Price_USD'] = pd.to_numeric(df['Price_USD'], errors='coerce')
df['Horsepower'] = pd.to_numeric(df['Horsepower'], errors='coerce')

In [29]:
df_scale = df[['Price_USD', 'Horsepower']].dropna()

In [30]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
df_minmax = df_scale.copy()

df_minmax[['Price_USD', 'Horsepower']] = minmax.fit_transform(df_minmax)

df_minmax.head()

0  Price_USD  Horsepower
0   0.596209    0.901701
1   0.648348    0.183365
2   0.623682    0.075614
3   0.380367    0.572779
4   0.682406    0.141777


TAsk 5: Apply PCA and interpret explained variance

In [ ]:
# Make sure columns are numeric
df['Price_USD'] = pd.to_numeric(df['Price_USD'], errors='coerce')
df['Horsepower'] = pd.to_numeric(df['Horsepower'], errors='coerce')

# Select and clean data
df_pca = df[['Price_USD', 'Horsepower']].dropna()

# Standardize first (required before PCA)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_zscore = scaler.fit_transform(df_pca)

# Apply PCA
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
principal_components = pca.fit_transform(df_zscore)

print("Explained Variance Ratio:", pca.explained_variance_ratio_)

Explained Variance Ratio: [0.55247013 0.44752987]